export const CHAIN_NAMES = new Set<string>([
  "mcdonald's",
  'burger king',
  "wendy's",
  'taco bell',
  'chipotle',
  'subway',
  "domino's",
  'pizza hut',
  "papa john's",
  'little caesars',
  'kfc',
  'popeyes',
  'chick-fil-a',
  'five guys',
  'shake shack',
  'in-n-out',
  'whataburger',
  'sonic',
  "arby's",
  'jack in the box',
  "hardee's",
  "carl's jr",
  'dairy queen',
  'baskin-robbins',
  'dunkin',
  'starbucks',
  'tim hortons',
  'panera bread',
  'panda express',
  'olive garden',
  'red lobster',
  "applebee's",
  "chili's",
  'tgi fridays',
  'ihop',
  "denny's",
  'waffle house',
  'cracker barrel',
  'bob evans',
  'golden corral',
  'outback steakhouse',
  'texas roadhouse',
  'longhorn steakhouse',
  'red robin',
  'cheesecake factory',
  "pf chang's",
  'benihana',
  'sushi express',
  'noodles & company',
  "jason's deli",
  'corner bakery',
  'einstein brothers',
  'great clips',
  "jimmy john's",
  "jersey mike's",
  'firehouse subs',
  'potbelly',
  'quiznos',
  "mcalister's deli",
  "zaxby's",
  "raising cane's",
  'wingstop',
  'buffalo wild wings',
  'hooters',
  'dine brands',
]);

export function isChain(name: string): boolean {
  const lowerName = name.toLowerCase();
  for (const chainName of CHAIN_NAMES) {
    if (lowerName.includes(chainName)) {
      return true;
    }
  }
  return false;
}
